### ISSUE TITLE
Grunt runDebug error

### ISSUE THREAD

**Issue by pertrai1** [auchenberg/chrome-devtools-app#26]
Hi, I tried to run the `grunt runDebug` and I got the following error that I don't understand:

```
grunt runDebug                                                                                        master d8089aa
Running "shell:runAppDebug" (shell) task
[10525:0110/045416:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[10526:0110/045416:ERROR:breakpad_mac.mm(238)] Breakpad initializaiton failed
[10524:0110/045416:INFO:CONSOLE(35)] "Uncaught Error: Module did not self-register.", source: /Users/robsimpson/Projects/chrome-devtools-app/node_modules/mdns/lib/dns_sd.js (35)
[10524:0110/045416:INFO:CONSOLE(4117)] "Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:nomod] Module 'app' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.8/$injector/nomod?p0=app
    at file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:63:12
    at file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:1764:17
    at ensure (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:1688:38)
    at module (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:1762:14)
    at file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:4094:22
    at forEach (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:323:20)
    at loadModules (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:4078:5)
    at createInjector (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:4004:11)
    at doBootstrap (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:1446:20)
    at bootstrap (file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js:1467:12)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'app'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.8%2F%24injector%2Fnomod%3Fp0%3Dapp%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1764%3A17%0A%20%20%20%20at%20ensure%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1688%3A38)%0A%20%20%20%20at%20module%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1762%3A14)%0A%20%20%20%20at%20file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A4094%3A22%0A%20%20%20%20at%20forEach%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A4078%3A5)%0A%20%20%20%20at%20createInjector%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A4004%3A11)%0A%20%20%20%20at%20doBootstrap%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1446%3A20)%0A%20%20%20%20at%20bootstrap%20(file%3A%2F%2F%2FUsers%2Frobsimpson%2FProjects%2Fchrome-devtools-app%2Fapp%2Flib%2Fbower_components%2Fangular%2Fangular.js%3A1467%3A12)", source: file:///Users/robsimpson/Projects/chrome-devtools-app/app/lib/bower_components/angular/angular.js (4117)
```

**Comment by auchenberg** [comment]
Master is in a more stable state now. Can you please try again?
