### ISSUE TITLE
Grunt build error

### ISSUE THREAD

**Issue by pertrai1** [auchenberg/chrome-devtools-app#27]
I tried to run `grunt build` and I got the following error:

```
grunt build                                                                                           master d8089aa
Running "nodewebkit:src" (nodewebkit) task
Latest Version: v0.11.5
Using v0.11.5
Create cache folder in /Users/robsimpson/Projects/chrome-devtools-app/cache/0.11.5
Downloading: http://dl.node-webkit.org/v0.11.5/node-webkit-v0.11.5-osx-ia32.zip
  downloading [====================] 100% 0.0s

Create release folder in /Users/robsimpson/Projects/chrome-devtools-app/build/Chrome DevTools/osx
Fatal error: Missing macPlist property 'NSHumanReadableCopyright'
Error: Missing macPlist property 'NSHumanReadableCopyright'
    at /Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/lib/utils.js:176:23
    at Array.forEach (native)
    at Object.module.exports.editPlist (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/lib/utils.js:174:11)
    at NwBuilder.handleMacApp (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/lib/index.js:490:28)
    at tryCatch1 (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/util.js:63:19)
    at Promise$_callHandler [as _callHandler] (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:695:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:711:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:868:14)
    at Promise$_settlePromises [as _settlePromises] (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/promise.js:1006:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/Users/robsimpson/Projects/chrome-devtools-app/node_modules/grunt-node-webkit-builder/node_modules/node-webkit-builder/node_modules/bluebird/js/main/async.js:74:12)
```

**Comment by auchenberg** [comment]
Which version of node are you on? I'm on ``v0.10.35`` without any issues on master.

**Comment by auchenberg** [comment]
Master is in a more stable state now. Can you please try again?
